config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires
  resources :contents
  resources :questionnaire_items do
    put :sort, on: :collection
    put :createbreak, on: :collection
  end
  namespace :api do 
    resources :questionnaires, defaults: { format: 'json' }
    resources :questions, defaults: { format: 'json' }
    resources :question_inputs, defaults: { format: 'json' }
    resources :sections, defaults: { format: 'json' } do
      resources :feedbacks
      get 'feedback/:score', to: 'feedbacks#score'
    end
    resources :feedbacks, defaults: { format: 'json' } do
      get '/:score', to: 'feedbacks#show'
    end
    resources :questionnaire_items, defaults: { format: 'json' }
  end

  resources :question_sections
  resources :sections do
    resources :questions
    resources :feedbacks
    resources :question_inputs
    put :sort, on: :collection
  end
  resources :feedbacks
  root 'questionnaire_items#index'
  resources :questions do
    put :sort, on: :collection
  end
  resources :users do
    put :authorise, on: :collection
  end
  resources :question_inputs

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :sections, :through => :question_sections
	belongs_to :section
	belongs_to :questionnaire_items
	has_many :question_sections
	has_many :question_inputs
 	default_scope { order(id: :asc) }

 	accepts_nested_attributes_for :section, :reject_if => :all_blank, allow_destroy: true
 	accepts_nested_attributes_for :question_sections, :reject_if => :all_blank, allow_destroy: true
 	accepts_nested_attributes_for :question_inputs, :reject_if => :all_blank, allow_destroy: true
end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < ApplicationController
	def index
		#render json: Question.all
		@question = Question.all
		respond_to do |format|
		  format.json  { render :json => @question.to_json(:include => [:question_inputs, :sections]), :callback => params['callback']}
		end
	end

	def show
		list = Question.find(params[:id])
		render json: list
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authorize
  
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # GET /questions/1/edit
  def section
    @question = @section.questions
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    # Get new order value
    @order = QuestionnaireItem.maximum("order") + 1

    respond_to do |format|
      if @question.save
        format.html { redirect_to questionnaire_items_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }

        @questionnaire_item =  QuestionnaireItem.new(:question_id => @question.id, :content_id => '', :break => '', :order => @order, :questionnaire_id => 1)
        @questionnaire_item.save

      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_items_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def sort
  #   params[:order].each do |key,value|
  #     Question.find(value[:id]).update_attribute(:order,value[:order])
  #   end
  #   render :nothing => true
  # end

  def sort
    params[:order].each do |key,value|
        questions = Question.includes(:question_sections).find(value[:id])
        questions.question_sections.each { |q| q.update_attribute(:order,value[:order]) }
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :low_label, :high_label,
        question_sections_attributes: [:id, :question_id, :section_id, :weight, :order, :_destroy ],
        question_inputs_attributes: [:id, :question_id, :order, :input, :_destroy ])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row row--item">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>

  <fieldset>
    <div class="small-9 columns">
      <h3>Answer Options</h3>
    </div>
    <div class="small-12 columns">
      <p>Add the possible responses for the question here</p>
    </div>
    <%= f.fields_for :question_inputs do |question_input| %>
      <%= render 'question_input_fields', f: question_input %>
    <% end %>
    <div class="small-12 columns">
      <%= link_to_add_association 'Add option', f, :question_inputs, class: "button"  %>
    </div>
  </fieldset>

  <fieldset class="field ">
    <div class="small-9 columns">
      <h3>Labels</h3> 
    </div>
    <div class="small-12 columns">
      <p>Labels to display on the left and right of the options (ie 'Never' and 'Always')</p>
    </div>
    <div class="small-6 columns">
      <div class="section-contain">
        <%= f.label :low_label %><br>
        <%= f.text_field :low_label %>
      </div>
    </div>
    <div class="small-6 columns">
      <div class="section-contain">
        <%= f.label :high_label %><br>
        <%= f.text_field :high_label %>
      </div>
    </div>
  </fieldset>

  <fieldset>
   <div class="small-9 columns">
      <h3>Sections</h3> 
    </div>
    <div class="small-12 columns">
     <p>A question could potentially influence the results in multiple sections</p>
    </div>
    <%= f.fields_for :question_sections do |question_section| %>
      <%= render 'question_section_fields', f: question_section %>
    <% end %>
    <div class="small-12 columns">
      <%= link_to_add_association 'Add to section', f, :question_sections, class: "button" %>
    </div>
  </fieldset>

  <fieldset>
    <div class="small-12 columns actions">
      <%= f.submit 'Submit', :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/questions/_question_input_fields.html.erb
<div class="nested-fields small-4 columns">
	<div class="section-contain clearfix">

		<%= link_to_remove_association "", f, class: 'fa fa-times remove-field' %>
		
		<div class="small-8 columns">
			<%= f.label "Answer Option"  %>
			<%= f.text_area :input %>
		</div>

		<div class="small-4 columns">
			<%= f.label "Score" %>
			<%= f.text_area :order %>
		</div>

	</div>
	
</div>

app/views/questions/_question_section_fields.html.erb
<div class="nested-fields small-4 columns">
	<div class="section-contain clearfix">
		
		<div class="small-6 columns">
			<%= f.label :section_id %>
			<%= f.collection_select :section_id, Section.all, :id, :name, {} %>
		</div>

		<div class="small-6 columns">
			<%= f.label :weight %>
			<%= f.text_field :weight %>
		</div>
		
		<%= link_to_remove_association "", f, class: 'fa fa-times remove-field' %>

	</div>
</div>

app/views/questions/edit.html.erb
<h1 class="heading-padding">Editing Question</h1>

<%= render 'form' %>

<!-- <div class="small-12 columns">
	<%= link_to 'Show', @question %> |
	<%= link_to 'Back', questions_path %>
</div> -->

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="small-12 medium-9 column">
        <h1>Questions</h1>
    </div>
    <div class="small-12 medium-3 column text-right">
        <%= link_to 'New Question', new_question_path, class: "button" %>
    </div>
</div>

<div class="sortable">
  <% @questions.each do |question| %>
    <div class="row question row--item" data-id="<%= question.id %>" >
        <div class="small-9 columns"><%= link_to question.question, edit_question_path(question) %></div>
        <div class="small-3 columns text-right end">
            <% question.sections.each do |section| %>
                 <%= link_to Section.find(section.id).name, section_path(section.id) %>
            <% end %>
            <div class="row--item__controls">
                <%= link_to '', edit_question_path(question), class: "edit fa fa-pencil" %>
                <%= link_to '', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
            </div>
        </div>
        <!-- <div style="dis;" class="small-2 medium-1 text-right columns"><%= link_to '', edit_question_path(question), class: "edit fa fa-pencil" %>
        <%= link_to '', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %></div> -->
    </div>
  <% end %>
</div>

<br>

app/views/questions/new.html.erb
<h1 class="heading-padding">New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>

  <% @question.question_sections.each do |question_section| %>
        <%= question_section.weight %>
  <% end %>
</p>



<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>