config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires
  resources :contents
  resources :questionnaire_items do
    put :sort, on: :collection
    put :createbreak, on: :collection
  end
  namespace :api do 
    resources :questionnaires, defaults: { format: 'json' }
    resources :questions, defaults: { format: 'json' }
    resources :question_inputs, defaults: { format: 'json' }
    resources :sections, defaults: { format: 'json' } do
      resources :feedbacks
      get 'feedback/:score', to: 'feedbacks#score'
    end
    resources :feedbacks, defaults: { format: 'json' } do
      get '/:score', to: 'feedbacks#show'
    end
    resources :questionnaire_items, defaults: { format: 'json' }
  end

  resources :question_sections
  resources :sections do
    resources :questions
    resources :feedbacks
    resources :question_inputs
    put :sort, on: :collection
  end
  resources :feedbacks
  root 'questionnaire_items#index'
  resources :questions do
    put :sort, on: :collection
  end
  resources :users do
    put :authorise, on: :collection
  end
  resources :question_inputs

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  

end

app/models/questionnaire_item.rb
class QuestionnaireItem < ActiveRecord::Base
	belongs_to :question
	belongs_to :content
end

app/controllers/api/questionnaire_items_controller.rb
class Api::QuestionnaireItemsController < ApplicationController
	def index
		@questionnaire_items = QuestionnaireItem.includes(:question, :content).all.order(:order)
		respond_to do |format|
		  format.json  { render :json => @questionnaire_items.to_json( :include => [ :content, question: {include: [:question_inputs, :sections]} ] ), :callback => params['callback']}
		  #format.json  { render :json => @questionnaires.to_json(:include => [ questionnaire_items: {include: :question}, questionnaire_items: {include: :content} ], ), :callback => params['callback']}

		end

	end

	def show
		@section = Section.find(params[:id])
		@questions = @section.questions
		respond_to do |format|
		  format.json  { render :json => @section.to_json(:include => [:questions]), :callback => params['callback']}
		end
	end

	def full
		render json: Section.all
	end

end

app/controllers/questionnaire_items_controller.rb
class QuestionnaireItemsController < ApplicationController
  before_action :set_questionnaire_item, only: [:show, :edit, :update, :destroy]

  # GET /questionnaire_items
  # GET /questionnaire_items.json
  def index
    # @questionnaire_items = QuestionnaireItem.all
    # @questions = Question.all
    # @content = Content.all

    @questionnaire_items = QuestionnaireItem.includes(:question, :content).all.order(:order)
    respond_to do |format|
       format.json
       format.html
     end
    # @questionnaire_items.each do |QuestionnaireItem|
    #      QuestionnaireItem.question
    # end
  end

  # GET /questionnaire_items/1
  # GET /questionnaire_items/1.json
  def show
  end

  # GET /questionnaire_items/new
  def new
    @questionnaire_item = QuestionnaireItem.new
  end

  # GET /questionnaire_items/1/edit
  def edit
  end

  # POST /questionnaire_items
  # POST /questionnaire_items.json
  def create
    @questionnaire_item = QuestionnaireItem.new(questionnaire_item_params)

    respond_to do |format|
      if @questionnaire_item.save
        format.html { redirect_to @questionnaire_item, notice: 'Questionnaire item was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire_item }
      else
        format.html { render :new }
        format.json { render json: @questionnaire_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def createbreak
    # Get new order value
    @order = QuestionnaireItem.maximum("order") + 1

    # Create break as question item
    @questionnaire_item =  QuestionnaireItem.new(:question_id => '', :content_id => '', :break => 1, :order => @order, :questionnaire_id => 1)
    @questionnaire_item.save

    render :nothing => true
  end

  # PATCH/PUT /questionnaire_items/1
  # PATCH/PUT /questionnaire_items/1.json
  def update
    respond_to do |format|
      if @questionnaire_item.update(questionnaire_item_params)
        format.html { redirect_to @questionnaire_item, notice: 'Questionnaire item was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire_item }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaire_items/1
  # DELETE /questionnaire_items/1.json
  def destroy
    @questionnaire_item.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_items_url, notice: 'Questionnaire item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    params[:order].each do |key,value|
        # questions = Question.includes(:question_sections).find(value[:id])
        # questions.question_sections.each { |q| q.update_attribute(:order,value[:order]) }

        QuestionnaireItem.find(value[:id]).update_attribute(:order,value[:order])
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire_item
      @questionnaire_item = QuestionnaireItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_item_params
      params.require(:questionnaire_item).permit(:question_id, :content_id, :break, :order)
    end
end

app/helpers/questionnaire_items_helper.rb
module QuestionnaireItemsHelper
end

app/views/questionnaire_items/_form.html.erb
<%= form_for(@questionnaire_item) do |f| %>
  <% if @questionnaire_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire_item.errors.count, "error") %> prohibited this questionnaire_item from being saved:</h2>

      <ul>
      <% @questionnaire_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :content_id %><br>
    <%= f.number_field :content_id %>
  </div>
  <div class="field">
    <%= f.label :break %><br>
    <%= f.check_box :break %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaire_items/edit.html.erb
<h1 class="heading-padding">Editing Questionnaire Item</h1>

<%= render 'form' %>

app/views/questionnaire_items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="small-12 medium-3 column">
        <h1>Questionnaire</h1>
    </div>
    <div class="small-12 medium-6 column text-right">
        <%= link_to 'New Question', new_question_path, class: "button" %>
        <%= link_to 'New Content', new_content_path, class: "button" %>
        <a class="button create-break" href="#">Insert break</a>
    </div>
</div>

<% @i = 1 %> 

<div class="sortable">
    <% @questionnaire_items.each do |questionnaire_item| %>

      <% if questionnaire_item.question %>
        <div class="row question question__questionnaire row--item" data-id="<%= questionnaire_item.id %>" >
      <% elsif questionnaire_item.content %>
        <div class="row content row--item" data-id="<%= questionnaire_item.id %>" >
       <% else %>
        <div class="row break row--item" data-id="<%= questionnaire_item.id %>" >
      <% end %>

        <% if questionnaire_item.question %>
          <div class="small-9 columns">
            <div class="row--item__order">
              <%= @i %>
            </div>
            <%= link_to questionnaire_item.question.question, edit_question_path(questionnaire_item.question) %>
          </div>
          <% @i = @i+1 %>
        <% elsif questionnaire_item.content %>
          <div class="small-9 columns"><%= questionnaire_item.content.heading %></div>
        <% else %>
          <div class="small-9 columns">Break - New page</div>
        <% end %>
        <div class="small-3 columns text-right end">
          <% if questionnaire_item.question %>
            <div class="row--item__controls">
                <%= link_to '', edit_question_path(questionnaire_item.question), class: "edit fa fa-pencil" %>
                <%= link_to '', questionnaire_item.question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
            </div>
          <% elsif questionnaire_item.content %>
             <div class="row--item__controls">
                <%= link_to '', edit_content_path(questionnaire_item.content), class: "edit fa fa-pencil" %>
                <%= link_to '', questionnaire_item.content, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
            </div>
          <% else %>
            <div class="row--item__controls">
              <%= link_to '', questionnaire_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
            </div>
        <% end %>
        </div>
      </div>      
    <% end %>
</div>

app/views/questionnaire_items/new.html.erb
<h1>New Questionnaire Item</h1>

<%= render 'form' %>

app/views/questionnaire_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @questionnaire_item.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @questionnaire_item.content_id %>
</p>

<p>
  <strong>Break:</strong>
  <%= @questionnaire_item.break %>
</p>

<p>
  <strong>Order:</strong>
  <%= @questionnaire_item.order %>
</p>

<%= link_to 'Edit', edit_questionnaire_item_path(@questionnaire_item) %> |
<%= link_to 'Back', questionnaire_items_path %>