config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires
  resources :contents
  resources :questionnaire_items do
    put :sort, on: :collection
    put :createbreak, on: :collection
  end
  namespace :api do 
    resources :questionnaires, defaults: { format: 'json' }
    resources :questions, defaults: { format: 'json' }
    resources :question_inputs, defaults: { format: 'json' }
    resources :sections, defaults: { format: 'json' } do
      resources :feedbacks
      get 'feedback/:score', to: 'feedbacks#score'
    end
    resources :feedbacks, defaults: { format: 'json' } do
      get '/:score', to: 'feedbacks#show'
    end
    resources :questionnaire_items, defaults: { format: 'json' }
  end

  resources :question_sections
  resources :sections do
    resources :questions
    resources :feedbacks
    resources :question_inputs
    put :sort, on: :collection
  end
  resources :feedbacks
  root 'questionnaire_items#index'
  resources :questions do
    put :sort, on: :collection
  end
  resources :users do
    put :authorise, on: :collection
  end
  resources :question_inputs

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  

end

app/views/shared/_header.html.erb
<header class="regular header-small" role="banner">
	<div class="main header">
		<div class="">
			<div class="logo">
					<h1 class="img"><a href="/"><img src="http://connected.tearfund.org/images/mainsite5/logo@2x.png" alt="Tearfund"></a></h1>
			</div>
			<h1 class="sub-brand">Connected Church</h1>
			
			<div class="inline-header-items">
				<div class="header-inline header-login">
					 <% if current_user %>
				      Hi <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
				    <% else %>
				      <%= link_to 'Login', '/login' %> | <%= link_to 'Login', '/signup' %>
				    <% end %>
				</div>
			</div>
		</div>
	</div>
</header>

app/views/shared/_menu.html.erb
<ul class="side-nav menu">
  <li class="<%= active_class(questionnaire_items_path) %>">
  	<%= link_to(raw('<i class="fa fa-question" aria-hidden="true"></i> Questionnaire'), questionnaire_items_path, class: "menu__questions")  %>
  </li>
  <li class="<%= active_class(questions_path) %>">
  	<%= link_to(raw('<i class="fa fa-question" aria-hidden="true"></i> Questions'), questions_path, class: "menu__questions")  %>
  </li>
  <li class="<%= active_class(sections_path) %> <%= parent_nav_is_active?(sections_path) %> ">
  	<%= link_to(raw('<i class="fa fa-bars" aria-hidden="true"></i> Sections'), sections_path, class: "menu__sections")  %>
  	<% @sections = Section.all %>
  	<ul class="menu sub-menu">
	  	<% @sections.each do |section| %>
	      <li class="<%= active_class(section) %>">
	        <%= link_to section.name, section %>
	        <ul class="menu sub-menu">
	        	<li class="<%= active_class(section) %>">
	        		<%= link_to 'Questions', section %>
	        	</li>
	        	<li class="<%= active_class([section, :feedbacks]) %>">
	        		<%= link_to 'Feedbacks', [section, :feedbacks] %>
	        	</li>
	        </ul>
	      </li>
	    <% end %>
	  </ul>
  </li>
  <li class="<%= active_class(users_path) %>">
  	<%= link_to(raw('<i class="fa fa-user" aria-hidden="true"></i> Users'), users_path, class: "menu__users")  %>
  </li>
</ul>