config/routes.rb
Rails.application.routes.draw do
  
  resources :questionnaires
  resources :contents
  resources :questionnaire_items do
    put :sort, on: :collection
    put :createbreak, on: :collection
  end
  namespace :api do 
    resources :questionnaires, defaults: { format: 'json' }
    resources :questions, defaults: { format: 'json' }
    resources :question_inputs, defaults: { format: 'json' }
    resources :sections, defaults: { format: 'json' } do
      resources :feedbacks
      get 'feedback/:score', to: 'feedbacks#score'
    end
    resources :feedbacks, defaults: { format: 'json' } do
      get '/:score', to: 'feedbacks#show'
    end
    resources :questionnaire_items, defaults: { format: 'json' }
  end

  resources :question_sections
  resources :sections do
    resources :questions
    resources :feedbacks
    resources :question_inputs
    put :sort, on: :collection
  end
  resources :feedbacks
  root 'questionnaire_items#index'
  resources :questions do
    put :sort, on: :collection
  end
  resources :users do
    put :authorise, on: :collection
  end
  resources :question_inputs

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  

end

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :questions, :through => :question_sections
	has_many :question_inputs, :through => :questions
	has_many :question_sections
	has_many :feedbacks

  	accepts_nested_attributes_for :feedbacks, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/api/sections_controller.rb
class Api::SectionsController < ApplicationController
	def index
		@section = Section.all
		respond_to do |format|
		  format.json  { render :json => @section.to_json(:include => [questions: {include: :question_inputs}], ), :callback => params['callback']}
		end

	end

	def show
		@section = Section.find(params[:id])
		@questions = @section.questions
		respond_to do |format|
		  format.json  { render :json => @section.to_json(:include => [:questions]), :callback => params['callback']}
		end
	end

	def full
		render json: Section.all
	end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_filter :authorize
  
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @sections = Section.find(params[:id])
    @questions = @section.questions
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    params[:order].each do |key,value|
        # questions = Question.includes(:question_sections).find(value[:id])
        # questions.question_sections.each { |q| q.update_attribute(:order,value[:order]) }

        QuestionSections.find(value[:id]).update_attribute(:order,value[:order])
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, 
        feedbacks_attributes: [:id, :name, :text, :low, :height, :_destroy ])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_feedback_fields.html.erb
  <%= f.text_area :name %>
<%= f.text_area :text %>
<%= f.text_area :low %>
  <%= f.text_area :high %>
  <%= f.submit :done, :as => :boolean %>
  

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row row--item">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>


<fieldset>
  <div class="">
    <h3>Feedback for section</h3>
  </div>
  <% @section.feedbacks.each do |feedback| %> 
    <div class="row row--item">
      <div class="small-9 columns"><%= link_to feedback.name, edit_feedback_path(feedback) %> </div>
      <div class="small-3 columns text-right end">
        <span class="secondary">Scoring <%= feedback.low %> - <%= feedback.high %></span>
        <div class="row--item__controls">
            <%= link_to '', edit_feedback_path(feedback), class: "edit fa fa-pencil" %>
            <%= link_to '', feedback, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
        </div>
      </div>
    </div>
  <% end %>
</fieldset>

<!--  <fieldset id="recipe-ingredients">
    <ol>
      <%= f.fields_for :feedbacks do |feedback| %>
        <%= render 'feedback_fields', f: feedback %>
      <% end %>
    </ol>
    <%= link_to_add_association 'add feedback', f, :feedbacks %>
  </fieldset>  -->

  <div class="actions">
    <%= f.submit 'Submit', :class => 'button' %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1 class="heading-padding">Editing Section</h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="small-12 medium-9 column">
      <h1>Sections</h1>
    </div>
    <div class="small-12 medium-3 column text-right">
      <%= link_to 'New Section', new_section_path, class: "button" %>
    </div>
</div>


<% @sections.each do |section| %>
  <div class="row section row--item">
    <div class="small-9 columns"><%= link_to section.name, edit_section_path(section) %> <span class="secondary">| <%= section.questions.size %> Questions </span></div>
    <div class="small-3 columns text-right end">
            <span class="secondary"><%= link_to 'Questions', section %> | <%= link_to 'Feedbacks', [section, :feedbacks]  %></span>
            <div class="row--item__controls">
                <%= link_to '', edit_section_path(section), class: "edit fa fa-pencil" %>
                <%= link_to '', section, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-times' %>
            </div>
        </div>
  </div>
<% end %>

app/views/sections/new.html.erb
<h1 class="heading-padding">New Section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="small-12 medium-9 column">
      <h1><%= @section.name %> Questoins</h1>
    </div>
    <div class="small-12 medium-3 column text-right">
      <%= link_to 'Add New', new_section_path, class: "button" %>
    </div>
</div>

<div class="sortable">
	<% @questions.each do |question| %> 
	  <div class="row question question__questionnaire section row--item" data-qsid="<%= question.question_sections.detect{|qc| qc.section_id == @section.id }.id %>" data-id="<%= question.id %>" data-position="<%= question.question_sections.detect{|qc| qc.section_id == @section.id }.order %>" data-section="<%= @section.id %>">
	        <div class="small-9 columns">
	        	<div class="row--item__order">
	        		<%= question.question_sections.detect{|qc| qc.section_id == @section.id }.order %>
	        	</div>
	        	<%= link_to question.question, question %>
	        </div>
	        <div class="small-3 columns text-right end">
	        	<div class="row--item__controls">
	        		<%= link_to '', edit_question_path(question), class: "fa fa-pencil" %>
	       	 		<%= link_to '', question, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-times" %>
	       	 	</div>
	       	</div>
	    </div>
	<% end %>
</div>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>